Repository moevm/mse1h2024-cv-tasks, pull requests merged in 2024-03, with the labels that each got.

#12 DatasetInterface
  dataset/DatasetInterface.py
  dataset/__init__.py
  requirements.txt
Labels: iteration 2, need changes, need check

#13 Metrics interface
  TestMetrics.py
  requirements.txt
  src/metrics/MetricsInterface.py
  src/metrics/PrecisionChecker.py
  src/metrics/__init__.py
Labels: iteration 2, need changes

#18 ignore files
  .dockerignore
  .gitignore
Labels: iteration 2

#19 Реализация метрик относительно интерфейса
  TestMetrics.py
  src/dataset/DatasetInterface.py
  src/dataset/__init__.py
  src/metrics/AccuracyChecker.py
  src/metrics/F1ScoreChecker.py
  src/metrics/ROCAUCChecker.py
  src/metrics/RecallChecker.py
Labels: iteration 2

#20 add docker compose
  docker-compose.yaml
Labels: iteration 2

#23 Base container
  Dockerfile
  requirements.txt
Labels: iteration 2, need changes

#28 Tests (only metrics)
  test/TestDatasets.py
  test/TestMetrics.py
Labels: bug, iteration 2, need check
